language: python
python:
  - "3.5"
dist: trusty
sudo: required
cache:
  pip: true
  directories:
    - $HOME/.ethash
env:
  matrix:
    - TOX_ENV=py27-stdlib GETH_BINARY="$TRAVIS_BUILD_DIR/geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth"
    - TOX_ENV=py34-stdlib GETH_BINARY="$TRAVIS_BUILD_DIR/geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth"
    - TOX_ENV=py35-stdlib GETH_BINARY="$TRAVIS_BUILD_DIR/geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth"
    - TOX_ENV=py27-gevent GETH_BINARY="$TRAVIS_BUILD_DIR/geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth"
    - TOX_ENV=py34-gevent GETH_BINARY="$TRAVIS_BUILD_DIR/geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth"
    - TOX_ENV=py35-gevent GETH_BINARY="$TRAVIS_BUILD_DIR/geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth"
    - TOX_ENV=flake8
before_install:
  - travis_retry sudo add-apt-repository -y ppa:gophers/archive
  - travis_retry sudo apt-get update
install:
  - travis_retry sudo apt-get install -y golang-1.7 build-essential
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
  - ./scripts/install_geth-1.5.4.sh
  - mkdir -p $HOME/.ethash
before_script:
  - ./geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth version
  - ./geth-versions/geth-1.5.4/go-ethereum-1.5.4/build/bin/geth makedag 0 $HOME/.ethash
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
