language: python
python:
  - "3.5"
dist: trusty
sudo: required
cache:
  - pip: true
  - directories:
    - $HOME/.ethash/
env:
  global:
    - GETH_BASE_INSTALL_PATH=$TRAVIS_BUILD_DIR
    - GOROOT=$HOME/go
matrix:
  include:
    # lint
    - python: "3.5"
      env: TOX_POSARGS="-e flake8"
    # installation
    - python: "2.7"
      env: TOX_POSARGS="-e py27-installation"
    - python: "3.4"
      env: TOX_POSARGS="-e py34-installation"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-installation"
    # geth 1.5.6
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.5.6
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.5.6
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.5.6
    # geth 1.5.7
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.5.7
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.5.7
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.5.7
    # geth 1.5.8
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.5.8
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.5.8
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.5.8
    # geth 1.5.9
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.5.9
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.5.9
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.5.9
    # geth 1.6.0
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.0
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.0
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.0
    # geth 1.6.1
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.1
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.1
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.1
    # geth 1.6.2
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.2
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.2
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.2
    # geth 1.6.3
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.3
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.3
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.3
    # geth 1.6.4
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.4
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.4
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.4
    # geth 1.6.5
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.5
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.5
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.5
    # geth 1.6.6
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.6
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.6
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.6
    # geth 1.6.7
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.6.7
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.6.7
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.6.7
    # geth 1.7.0
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.7.0
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.7.0
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.7.0
    # geth 1.7.2
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core" GETH_VERSION=v1.7.2
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core" GETH_VERSION=v1.7.2
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core" GETH_VERSION=v1.7.2
before_install:
  - travis_retry sudo add-apt-repository -y ppa:gophers/archive
  - travis_retry sudo apt-get update
  - mkdir -p $HOME/.ethash
install:
  - travis_retry sudo apt-get install -y golang-1.7 build-essential
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
  - pip install -e .
before_script:
  - export GOROOT=/usr/lib/go-1.7
  - python --version
  - if [ -n "$GETH_VERSION" ]; then python -m geth.install $GETH_VERSION; fi
  - if [ -n "$GETH_VERSION" ]; then export GETH_BINARY="$GETH_BASE_INSTALL_PATH/geth-$GETH_VERSION/bin/geth"; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY version; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY makedag 0 $HOME/.ethash; fi
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
