language: python
python:
  - "3.5"
dist: trusty
sudo: required
cache:
  - pip: true
  - directories:
    - $HOME/.ethash/
env:
  global:
    - GETH_BASE_INSTALL_PATH=$TRAVIS_BUILD_DIR
    - GOROOT=$HOME/go
  matrix:
    # installation
    - TOX_POSARGS="-e py27-installation"
    - TOX_POSARGS="-e py34-installation"
    - TOX_POSARGS="-e py35-installation"
    # geth 1.5.6
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.5.6
    # geth 1.5.7
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.5.7
    # geth 1.5.8
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.5.8
    # geth 1.5.9
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.5.9
    # geth 1.6.0
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.0
    # geth 1.6.1
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.1
    # geth 1.6.2
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.2
    # geth 1.6.3
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.3
    # geth 1.6.4
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.4
    # geth 1.6.5
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.5
    # geth 1.6.6
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.6
    # geth 1.6.7
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.6.7
    # geth 1.7.0
    - TOX_POSARGS="-e py27-stdlib -e py34-stdlib -e py35-stdlib -e py27-gevent -e py34-gevent -e py35-gevent" GETH_VERSION=v1.7.0
    # flake8
    - TOX_POSARGS="-e flake8"
before_install:
  - travis_retry sudo add-apt-repository -y ppa:gophers/archive
  - travis_retry sudo apt-get update
  - mkdir -p $HOME/.ethash
install:
  - travis_retry sudo apt-get install -y golang-1.7 build-essential
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
  - pip install -e .
before_script:
  - export GOROOT=/usr/lib/go-1.7
  - if [ -n "$GETH_VERSION" ]; then python3 -m geth.install $GETH_VERSION; fi
  - if [ -n "$GETH_VERSION" ]; then export GETH_BINARY="$GETH_BASE_INSTALL_PATH/geth-$GETH_VERSION/bin/geth"; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY version; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY makedag 0 $HOME/.ethash; fi
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
