version: 2.0

# heavily inspired by:
# https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: checkout fixtures submodule
        command: git submodule update --init --recursive
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - restore_cache:
        keys:
          - cache-v2-{{ arch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: |
          pip install --user tox
          pip install --user checksumdir
    - run:
        name: install golang-1.7
        command: ./.circleci/install_golang.sh
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - save_cache:
        paths:
          - ~/.ethash
        key: cache-v2-{{ arch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  py27-install-geth-v1.5.6:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.5.6
          TOXENV: py27-install-geth-v1.5.6
  py34-install-geth-v1.5.6:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.5.6
          TOXENV: py34-install-geth-v1.5.6
  py35-install-geth-v1.5.6:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.5.6
          TOXENV: py35-install-geth-v1.5.6

  py27-install-geth-v1.5.7:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.5.7
          TOXENV: py27-install-geth-v1.5.7
  py34-install-geth-v1.5.7:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.5.7
          TOXENV: py34-install-geth-v1.5.7
  py35-install-geth-v1.5.7:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.5.7
          TOXENV: py35-install-geth-v1.5.7

  py27-install-geth-v1.5.8:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.5.8
          TOXENV: py27-install-geth-v1.5.8
  py34-install-geth-v1.5.8:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.5.8
          TOXENV: py34-install-geth-v1.5.8
  py35-install-geth-v1.5.8:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.5.8
          TOXENV: py35-install-geth-v1.5.8

  py27-install-geth-v1.5.9:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.5.9
          TOXENV: py27-install-geth-v1.5.9
  py34-install-geth-v1.5.9:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.5.9
          TOXENV: py34-install-geth-v1.5.9
  py35-install-geth-v1.5.9:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.5.9
          TOXENV: py35-install-geth-v1.5.9

  py27-install-geth-v1.6.0:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.0
          TOXENV: py27-install-geth-v1.6.0
  py34-install-geth-v1.6.0:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.0
          TOXENV: py34-install-geth-v1.6.0
  py35-install-geth-v1.6.0:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.0
          TOXENV: py35-install-geth-v1.6.0

  py27-install-geth-v1.6.1:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.1
          TOXENV: py27-install-geth-v1.6.1
  py34-install-geth-v1.6.1:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.1
          TOXENV: py34-install-geth-v1.6.1
  py35-install-geth-v1.6.1:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.1
          TOXENV: py35-install-geth-v1.6.1

  py27-install-geth-v1.6.2:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.2
          TOXENV: py27-install-geth-v1.6.2
  py34-install-geth-v1.6.2:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.2
          TOXENV: py34-install-geth-v1.6.2
  py35-install-geth-v1.6.2:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.2
          TOXENV: py35-install-geth-v1.6.2

  py27-install-geth-v1.6.3:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.3
          TOXENV: py27-install-geth-v1.6.3
  py34-install-geth-v1.6.3:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.3
          TOXENV: py34-install-geth-v1.6.3
  py35-install-geth-v1.6.3:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.3
          TOXENV: py35-install-geth-v1.6.3

  py27-install-geth-v1.6.4:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.4
          TOXENV: py27-install-geth-v1.6.4
  py34-install-geth-v1.6.4:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.4
          TOXENV: py34-install-geth-v1.6.4
  py35-install-geth-v1.6.4:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.4
          TOXENV: py35-install-geth-v1.6.4

  py27-install-geth-v1.6.5:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.5
          TOXENV: py27-install-geth-v1.6.5
  py34-install-geth-v1.6.5:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.5
          TOXENV: py34-install-geth-v1.6.5
  py35-install-geth-v1.6.5:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.5
          TOXENV: py35-install-geth-v1.6.5

  py27-install-geth-v1.6.6:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.6
          TOXENV: py27-install-geth-v1.6.6
  py34-install-geth-v1.6.6:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.6
          TOXENV: py34-install-geth-v1.6.6
  py35-install-geth-v1.6.6:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.6
          TOXENV: py35-install-geth-v1.6.6

  py27-install-geth-v1.6.7:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.6.7
          TOXENV: py27-install-geth-v1.6.7
  py34-install-geth-v1.6.7:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.6.7
          TOXENV: py34-install-geth-v1.6.7
  py35-install-geth-v1.6.7:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.6.7
          TOXENV: py35-install-geth-v1.6.7

  py27-install-geth-v1.7.0:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.7.0
          TOXENV: py27-install-geth-v1.7.0
  py34-install-geth-v1.7.0:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.7.0
          TOXENV: py34-install-geth-v1.7.0
  py35-install-geth-v1.7.0:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.7.0
          TOXENV: py35-install-geth-v1.7.0

  py27-install-geth-v1.7.2:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.7.2
          TOXENV: py27-install-geth-v1.7.2
  py34-install-geth-v1.7.2:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.7.2
          TOXENV: py34-install-geth-v1.7.2
  py35-install-geth-v1.7.2:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.7.2
          TOXENV: py35-install-geth-v1.7.2

  py27-install-geth-v1.8.1:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          GETH_VERSION: v1.8.1
          TOXENV: py27-install-geth-v1.8.1
  py34-install-geth-v1.8.1:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          GETH_VERSION: v1.8.1
          TOXENV: py34-install-geth-v1.8.1
  py35-install-geth-v1.8.1:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          GETH_VERSION: v1.8.1
          TOXENV: py35-install-geth-v1.8.1

  py27-lint:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          TOXENV: py27-lint
  py34-lint:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV: py34-lint
  py35-lint:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35-lint


workflows:
  version: 2
  test:
    jobs:
      - py27-install-geth-v1.5.6
      - py34-install-geth-v1.5.6
      - py35-install-geth-v1.5.6

      - py27-install-geth-v1.5.7
      - py34-install-geth-v1.5.7
      - py35-install-geth-v1.5.7

      - py27-install-geth-v1.5.8
      - py34-install-geth-v1.5.8
      - py35-install-geth-v1.5.8

      - py27-install-geth-v1.5.9
      - py34-install-geth-v1.5.9
      - py35-install-geth-v1.5.9

      - py27-install-geth-v1.6.0
      - py34-install-geth-v1.6.0
      - py35-install-geth-v1.6.0

      - py27-install-geth-v1.6.1
      - py34-install-geth-v1.6.1
      - py35-install-geth-v1.6.1

      - py27-install-geth-v1.6.2
      - py34-install-geth-v1.6.2
      - py35-install-geth-v1.6.2

      - py27-install-geth-v1.6.3
      - py34-install-geth-v1.6.3
      - py35-install-geth-v1.6.3

      - py27-install-geth-v1.6.4
      - py34-install-geth-v1.6.4
      - py35-install-geth-v1.6.4

      - py27-install-geth-v1.6.5
      - py34-install-geth-v1.6.5
      - py35-install-geth-v1.6.5

      - py27-install-geth-v1.6.6
      - py34-install-geth-v1.6.6
      - py35-install-geth-v1.6.6

      - py27-install-geth-v1.6.7
      - py34-install-geth-v1.6.7
      - py35-install-geth-v1.6.7

      - py27-install-geth-v1.7.0
      - py34-install-geth-v1.7.0
      - py35-install-geth-v1.7.0

      - py27-install-geth-v1.7.2
      - py34-install-geth-v1.7.2
      - py35-install-geth-v1.7.2

      - py27-install-geth-v1.8.1
      - py34-install-geth-v1.8.1
      - py35-install-geth-v1.8.1

      - py27-lint
      - py34-lint
      - py35-lint
